# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 21:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Earthquake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usgs_id', models.CharField(max_length=100, unique=True)),
                ('eq_lat', models.FloatField()),
                ('eq_long', models.FloatField()),
                ('depth', models.FloatField()),
                ('mag', models.FloatField()),
                ('eq_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('mag',),
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('loc_lat', models.FloatField()),
                ('loc_long', models.FloatField()),
                ('radius', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserEarthquake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('earthquake_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_earthquakes', to='eq_map.Earthquake')),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_earthquakes', to='eq_map.Location')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_earthquakes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
