# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eq_map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='earthquake',
            name='location_id',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
